<a href="https://colab.research.google.com/github/RD191295/Tensorflow_Tutorials/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this Notbook we are going to cover some of most fundamentals concepts of tensors using TensorFLow



1.   Introduction to tensors
2.   Getting information from tensors
3.   Manipulating tensors
4.   Tensors & Numpy
5.   Using @tf.function (a way to speed up your regular functions)
6.   Using GPUS with Tensorflow(or TPUs)
7.   Excercises to try yourself




# Introduction to Tensors

In [1]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor( ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# create vector

vector = tf.constant([10,12])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 12], dtype=int32)>

In [5]:
# Check the number of dimensions of a vector( ndim stands for number of dimensions)
vector.ndim

1

In [6]:
# create matrix( has more than 1 dim)
matrix = tf.constant([[10,7],
                      [12,14]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12, 14]], dtype=int32)>

In [7]:
# Check the number of dimensions of a matrix( ndim stands for number of dimensions)
matrix.ndim

2

In [8]:
# create matrix ( specify dtype)
another_matrix = tf.constant([[10.,12.],
                              [12.,14.9]],dtype= tf.float16) # specify datatype
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10. , 12. ],
       [12. , 14.9]], dtype=float16)>

In [9]:
# what's number of dimension of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create tensors
tensor = tf.constant([[[1,2,3],
                       [3,4,5]],
                       [[4,5,6],
                        [7,8,9]],
                       [[1,2,45],
                        [1,3,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2, 45],
        [ 1,  3,  4]]], dtype=int32)>

In [11]:
# let's check dimensions of tensor
tensor.ndim

3

# Note :
* Scalar : a single Number
* Vector : a number with direction ( e.g. wind speed and direction)
* matrix : 2-dimesional array of numbers
* Tensor : an n-dimensional array of numbers(when n can be any number , a o-dimesional tensor is scalar,a 1-dimensional is vector)

### Creating tensors with tf.variable()

In [12]:
# create the same tensor with tf.variable() as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try change one of the elements in our changeable in changable_tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# Let's try change one of the elements in our changeable in unchangable_tensor

# unchangable_tensor[0].assign[7]
# unchangable_tensor

# with tf.constant you can not change value....

🔑**Note** : Rarely in practice will you need to decide whether to use tf.constant or tf.variable to create tensors. However ,if in doubt use tf.constant and change it later if needed

### Creating random tensors

##### Random tensors are tensors of some arbitary size which contain random numbers.

In [15]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

# Are they equal --- Yes
random_1,random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in tensor

In [16]:
# Shuffle a tensor ( valuble for when you want to shuffle your data so the inherent )
not_shuffled = tf.constant([[10,7],
                            [5,2],
                            [3,4]])
# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  2],
       [10,  7]], dtype=int32)>

In [17]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  2],
       [ 3,  4]], dtype=int32)>

🛠 **Excercise** : Read Tensorflow documentation on tensorflow random seed. create 5 tensors and shuffle them 

In [18]:
not_shuffled_1 = tf.Variable([[[10,23],[20,34]],
                              [[34,45],[56,45]],
                              [[23,34],[23,56]]])

# shffule it!!!
tf.random.shuffle(not_shuffled_1)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10, 23],
        [20, 34]],

       [[23, 34],
        [23, 56]],

       [[34, 45],
        [56, 45]]], dtype=int32)>

In [19]:
not_shuffled_2 = tf.constant([[[10,15],[24,56]],
                               [[34,45],[45,25]],
                              [[24,45],[45,67]]])

tf.random.shuffle(not_shuffled_2)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10, 15],
        [24, 56]],

       [[24, 45],
        [45, 67]],

       [[34, 45],
        [45, 25]]], dtype=int32)>

### Others ways to Make tensors

In [20]:
# create a tensor of all ones

tf.ones(shape=(13,4))

<tf.Tensor: shape=(13, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [21]:
# create a tensor of all zeroes

tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into tenosrs

###### The main differnce between Numpy arrays and tensorflow tensors is that tensors can be run on a GPU (much faster computing)

In [22]:
# you can also turn Numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # create numpy array from between 1 to 25

In [23]:
A = tf.constant(numpy_A, shape= (3, 2, 4))
A

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting More Information from tensors

* Shape --- tensor.shape
* Rank ---- tensor.ndim
* Axis or dimension---- temsor[0], tensor[:,1] etc
* size ---- tf.size

In [24]:
# create tensor with rank 4 ( 4 dimesions)

rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor                     

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [26]:
rank_4_tensor.shape,rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
# Get various attributes of our tensor

print("Datatype of every elements:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("Elements alomg the 0 axis:",rank_4_tensor.shape[0])
print("Elements alomg the last axis:",rank_4_tensor.shape[-1])
print("total Number of elements in our tensor",tf.size(rank_4_tensor).numpy())


Datatype of every elements: <dtype: 'float32'>
Number of dimensions (rank): 4
shape of tensor: (2, 3, 4, 5)
Elements alomg the 0 axis: 2
Elements alomg the last axis: 5
total Number of elements in our tensor 120


### Indexing Tensors

Tensors can be indexed just like Python Lists

In [28]:
#get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
# Get first element from each dimension from each index except for the final on

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
# Create ranke 2 tensor (2 Dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [35]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [37]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [39]:
# Alternative to tf.newaxis
tf.expand_dims (rank_2_tensor, axis = -1) # "-1" means expand the final dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors(tensor operations)
**Basic Operations**

`+`,`-`,`*`,`/`

In [41]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [42]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [43]:
# Multiplication also works
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [44]:
# Substraction operation
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [45]:
# We can use the tensorflow build-in function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplication 

Matrix Multiplication is one of most common tensor operation in machine learning  

In [46]:
# Matirx Multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

📓**Excercise** : Create two different matrix and do multiplication

In [49]:
# Tensor - 1
tensor_1 = tf.Variable([[1,2,5],
                        [7,2,1],
                        [3,3,3]])
tensor_1

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [50]:
# Tensor - 2
tensor_2 = tf.Variable([[3,5],
                        [6,7],
                        [1,8]])
tensor_2

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [51]:
# Multiplication of tensor_1 and tensor_2
tf.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [52]:
# tensor multiplication with python operator
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>