<a href="https://colab.research.google.com/github/RD191295/Tensorflow_Tutorials/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this Notbook we are going to cover some of most fundamentals concepts of tensors using TensorFLow



1.   Introduction to tensors
2.   Getting information from tensors
3.   Manipulating tensors
4.   Tensors & Numpy
5.   Using @tf.function (a way to speed up your regular functions)
6.   Using GPUS with Tensorflow(or TPUs)
7.   Excercises to try yourself




# Introduction to Tensors

In [1]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor( ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# create vector

vector = tf.constant([10,12])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 12], dtype=int32)>

In [5]:
# Check the number of dimensions of a vector( ndim stands for number of dimensions)
vector.ndim

1

In [6]:
# create matrix( has more than 1 dim)
matrix = tf.constant([[10,7],
                      [12,14]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12, 14]], dtype=int32)>

In [7]:
# Check the number of dimensions of a matrix( ndim stands for number of dimensions)
matrix.ndim

2

In [8]:
# create matrix ( specify dtype)
another_matrix = tf.constant([[10.,12.],
                              [12.,14.9]],dtype= tf.float16) # specify datatype
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10. , 12. ],
       [12. , 14.9]], dtype=float16)>

In [9]:
# what's number of dimension of another_matrix
another_matrix.ndim

2

In [13]:
# Let's create tensors
tensor = tf.constant([[[1,2,3],
                       [3,4,5]],
                       [[4,5,6],
                        [7,8,9]],
                       [[1,2,45],
                        [1,3,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2, 45],
        [ 1,  3,  4]]], dtype=int32)>

In [14]:
# let's check dimensions of tensor
tensor.ndim

3

# Note :
* Scalar : a single Number
* Vector : a number with direction ( e.g. wind speed and direction)
* matrix : 2-dimesional array of numbers
* Tensor : an n-dimensional array of numbers(when n can be any number , a o-dimesional tensor is scalar,a 1-dimensional is vector)