<a href="https://colab.research.google.com/github/RD191295/Tensorflow_Tutorials/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In this Notbook we are going to cover some of most fundamentals concepts of tensors using TensorFLow



1.   Introduction to tensors
2.   Getting information from tensors
3.   Manipulating tensors
4.   Tensors & Numpy
5.   Using @tf.function (a way to speed up your regular functions)
6.   Using GPUS with Tensorflow(or TPUs)
7.   Excercises to try yourself




# Introduction to Tensors

In [1]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor( ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# create vector

vector = tf.constant([10,12])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 12], dtype=int32)>

In [5]:
# Check the number of dimensions of a vector( ndim stands for number of dimensions)
vector.ndim

1

In [6]:
# create matrix( has more than 1 dim)
matrix = tf.constant([[10,7],
                      [12,14]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12, 14]], dtype=int32)>

In [7]:
# Check the number of dimensions of a matrix( ndim stands for number of dimensions)
matrix.ndim

2

In [8]:
# create matrix ( specify dtype)
another_matrix = tf.constant([[10.,12.],
                              [12.,14.9]],dtype= tf.float16) # specify datatype
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10. , 12. ],
       [12. , 14.9]], dtype=float16)>

In [9]:
# what's number of dimension of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create tensors
tensor = tf.constant([[[1,2,3],
                       [3,4,5]],
                       [[4,5,6],
                        [7,8,9]],
                       [[1,2,45],
                        [1,3,4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2, 45],
        [ 1,  3,  4]]], dtype=int32)>

In [11]:
# let's check dimensions of tensor
tensor.ndim

3

# Note :
* Scalar : a single Number
* Vector : a number with direction ( e.g. wind speed and direction)
* matrix : 2-dimesional array of numbers
* Tensor : an n-dimensional array of numbers(when n can be any number , a o-dimesional tensor is scalar,a 1-dimensional is vector)

### Creating tensors with tf.variable()

In [12]:
# create the same tensor with tf.variable() as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try change one of the elements in our changeable in changable_tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# Let's try change one of the elements in our changeable in unchangable_tensor

# unchangable_tensor[0].assign[7]
# unchangable_tensor

# with tf.constant you can not change value....

🔑**Note** : Rarely in practice will you need to decide whether to use tf.constant or tf.variable to create tensors. However ,if in doubt use tf.constant and change it later if needed

### Creating random tensors

##### Random tensors are tensors of some arbitary size which contain random numbers.

In [15]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

# Are they equal --- Yes
random_1,random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in tensor

In [16]:
# Shuffle a tensor ( valuble for when you want to shuffle your data so the inherent )
not_shuffled = tf.constant([[10,7],
                            [5,2],
                            [3,4]])
# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  2],
       [10,  7]], dtype=int32)>

In [17]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  2],
       [ 3,  4]], dtype=int32)>

🛠 **Excercise** : Read Tensorflow documentation on tensorflow random seed. create 5 tensors and shuffle them 

In [18]:
not_shuffled_1 = tf.Variable([[[10,23],[20,34]],
                              [[34,45],[56,45]],
                              [[23,34],[23,56]]])

# shffule it!!!
tf.random.shuffle(not_shuffled_1)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[23, 34],
        [23, 56]],

       [[34, 45],
        [56, 45]],

       [[10, 23],
        [20, 34]]], dtype=int32)>

In [19]:
not_shuffled_2 = tf.constant([[[10,15],[24,56]],
                               [[34,45],[45,25]],
                              [[24,45],[45,67]]])

tf.random.shuffle(not_shuffled_2)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[24, 45],
        [45, 67]],

       [[34, 45],
        [45, 25]],

       [[10, 15],
        [24, 56]]], dtype=int32)>

### Others ways to Make tensors

In [20]:
# create a tensor of all ones

tf.ones(shape=(13,4))

<tf.Tensor: shape=(13, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [21]:
# create a tensor of all zeroes

tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into tenosrs

###### The main differnce between Numpy arrays and tensorflow tensors is that tensors can be run on a GPU (much faster computing)

In [22]:
# you can also turn Numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # create numpy array from between 1 to 25

In [23]:
A = tf.constant(numpy_A, shape= (3, 2, 4))
A

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting More Information from tensors

* Shape --- tensor.shape
* Rank ---- tensor.ndim
* Axis or dimension---- temsor[0], tensor[:,1] etc
* size ---- tf.size

In [24]:
# create tensor with rank 4 ( 4 dimesions)

rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor                     

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [26]:
rank_4_tensor.shape,rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
# Get various attributes of our tensor

print("Datatype of every elements:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("Elements alomg the 0 axis:",rank_4_tensor.shape[0])
print("Elements alomg the last axis:",rank_4_tensor.shape[-1])
print("total Number of elements in our tensor",tf.size(rank_4_tensor).numpy())


Datatype of every elements: <dtype: 'float32'>
Number of dimensions (rank): 4
shape of tensor: (2, 3, 4, 5)
Elements alomg the 0 axis: 2
Elements alomg the last axis: 5
total Number of elements in our tensor 120


### Indexing Tensors

Tensors can be indexed just like Python Lists

In [28]:
#get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
# Get first element from each dimension from each index except for the final on

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# Create ranke 2 tensor (2 Dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [31]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [32]:
# add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
# Alternative to tf.newaxis
tf.expand_dims (rank_2_tensor, axis = -1) # "-1" means expand the final dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors(tensor operations)
**Basic Operations**

`+`,`-`,`*`,`/`

In [35]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [36]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [37]:
# Multiplication also works
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [38]:
# Substraction operation
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [39]:
# We can use the tensorflow build-in function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplication 

Matrix Multiplication is one of most common tensor operation in machine learning  

In [40]:
# Matirx Multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

📓**Excercise** : Create two different matrix and do multiplication

In [41]:
# Tensor - 1
tensor_1 = tf.Variable([[1,2,5],
                        [7,2,1],
                        [3,3,3]])
tensor_1

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [42]:
# Tensor - 2
tensor_2 = tf.Variable([[3,5],
                        [6,7],
                        [1,8]])
tensor_2

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [43]:
# Multiplication of tensor_1 and tensor_2
tf.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [44]:
# tensor multiplication with python operator
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [45]:
# Transpose operation
tf.transpose(tensor_1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 7, 3],
       [2, 2, 3],
       [5, 1, 3]], dtype=int32)>

**The Dot Product**
Matrix Multiplication is also refereed to as the dot product

you can perform matrix multiplication using:

* tf.matmul()
* tf.tensordot()
* @ operation


In [46]:
# Perform the dot product on tensor_1 and tensor_2

tf.tensordot(tensor_1, tensor_2, axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

🔑 Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up you will transpose(rather than reshape) one of the tensors to get satisify the matrix multiplication rules

## Changing the datatype of tensors

In [47]:
# Create a new tensor with default datatype
B = tf.constant([1.7,4.7])
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 4.7], dtype=float32)>,
 tf.float32)

In [48]:
C = tf.constant([7,10])
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [49]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 4.7], dtype=float16)>,
 tf.float16)

In [50]:
# change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [51]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [52]:
# Create New tensor
D = tf.constant([-4,-7,-10])
D

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ -4,  -7, -10], dtype=int32)>

In [53]:
# Get the absolute value
tf.abs(D)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  7, 10], dtype=int32)>

### Let's go through the following forms of aggergation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [54]:
# create another tensor
F = tf.constant([10,12,45],dtype = tf.float32)
F

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 12., 45.], dtype=float32)>

In [55]:
# Get the minimum
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [56]:
# Get the maximum
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-4>

In [57]:
# Get the mean of a tensor
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [58]:
# Get the sum of a tensor
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-21>

🛠 **Exercise:** Find the variance and standard deviation of our `D` tensor using Tensorflow methods.

In [59]:
# get the standar deviation of tensor
tf.math.reduce_std(F)

<tf.Tensor: shape=(), dtype=float32, numpy=16.048538>

In [60]:
# get the Variance of tensor
tf.math.reduce_variance(F)

<tf.Tensor: shape=(), dtype=float32, numpy=257.55557>

### Find the positional maximum and minimum



In [61]:
# Create a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [62]:
# find positional maximum 
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [63]:
# value at Index Maximum positional
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [64]:
# find positional  minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [65]:
# value at Index minimum positional
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor(removing all single dimensions)

In [66]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [67]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [68]:
G_squeezed = tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding

In [69]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be color name - red, green, blue, yellow

# one hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [70]:
# Specify custom values for one hot encoding --just for fun 

tf.one_hot(some_list, depth = 4, on_value="yo i love deep learning",
           off_value = "I also like to visit places")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'I also like to visit places',
        b'I also like to visit places', b'I also like to visit places'],
       [b'I also like to visit places', b'yo i love deep learning',
        b'I also like to visit places', b'I also like to visit places'],
       [b'I also like to visit places', b'I also like to visit places',
        b'yo i love deep learning', b'I also like to visit places'],
       [b'I also like to visit places', b'I also like to visit places',
        b'I also like to visit places', b'yo i love deep learning']],
      dtype=object)>

### Trying out more tensor math operations

In [71]:
# create new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [72]:
# find square of tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [73]:
# find the squareroot 
tf.sqrt(tf.cast(H, dtype = tf.bfloat16)) # type coversion due to sqrt not work with int

<tf.Tensor: shape=(9,), dtype=bfloat16, numpy=
array([1, 1.41406, 1.73438, 2, 2.23438, 2.45312, 2.64062, 2.82812, 3],
      dtype=bfloat16)>

In [74]:
# Find the log
tf.math.log(tf.cast(H, dtype = tf.bfloat16)) # type coversion due to log not work with int

<tf.Tensor: shape=(9,), dtype=bfloat16, numpy=
array([0, 0.691406, 1.10156, 1.38281, 1.60938, 1.78906, 1.94531, 2.07812,
       2.20312], dtype=bfloat16)>

### Tensor and Numpy


Tensorflow interacts beautifully with Numpy arrays.

In [75]:
# Create a tensor directly from a Numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [76]:
# Convert our tensor back to a Numpy array
np.array(J) , type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [77]:
# The default type of each are slightly different

numpy_J = tf.constant(np.array([3., 7., 5.]))
tensor_J = tf.constant([3., 7., 5.])

# check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUS

In [78]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [79]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



> 🔑 **Note**: If you have access to a CUDA-enabled GPUs then tensorflow will use whenever possible automatically

### 🛠 TensorFlow Fundamentals Exercises

* Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
* Find the shape, rank and size of the tensors you created in 1.
* Create two tensors containing random values between 0 and 1 with shape [5, 300].
* Multiply the two tensors you created in 3 using matrix multiplication.
* Multiply the two tensors you created in 3 using dot product.
* Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
* Find the min and max values of the tensor you created in 6 along the first axis.
* Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
* Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
* One-hot encode the tensor you created in 9.

In [80]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
Vector_A = tf.constant([1,23,45,6])
Vector_A

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1, 23, 45,  6], dtype=int32)>

In [81]:
Scalar_A = tf.constant([[1,23,45,6],[34,45,56,76]])
Scalar_A

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1, 23, 45,  6],
       [34, 45, 56, 76]], dtype=int32)>

In [82]:
tensor_A = tf.constant([[[43,45],[23,45]],
                        [[43,454],[34,20]]])
tensor_A

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 43,  45],
        [ 23,  45]],

       [[ 43, 454],
        [ 34,  20]]], dtype=int32)>

In [83]:
# Find the shape, rank and size of the tensors you created in 1.
Scalar_A.shape, Scalar_A.ndim, tf.size(Scalar_A)

(TensorShape([2, 4]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [84]:
Vector_A.shape, Vector_A.ndim, tf.size(Vector_A)

(TensorShape([4]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [85]:
tensor_A.shape, tensor_A.ndim, tf.size(tensor_A)

(TensorShape([2, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [94]:
# * Create two tensors containing random values between 0 and 1 with shape [5, 300].
tf.random.set_seed(42)
tensor_a = tf.random.uniform(shape = (5,300))
tensor_a

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [99]:
tensor_b = tf.random.uniform(shape = (5,300),dtype= tf.float32)
tensor_b

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7402308 , 0.33938193, 0.5692506 , ..., 0.08656633, 0.19666708,
        0.7110305 ],
       [0.13257599, 0.81292987, 0.01284087, ..., 0.02695906, 0.2927854 ,
        0.06227863],
       [0.282601  , 0.47868013, 0.77569485, ..., 0.28239357, 0.632112  ,
        0.44452012],
       [0.02029276, 0.7841259 , 0.16919017, ..., 0.26143157, 0.43055534,
        0.47421408],
       [0.2616079 , 0.00913954, 0.20257103, ..., 0.3548187 , 0.9939178 ,
        0.35239196]], dtype=float32)>

In [102]:
# Multiply the two tensors you created in 3 using matrix multiplication.
tensor_mul_ab = tf.matmul(tensor_a, tf.transpose(tensor_b))
tensor_mul_ab

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.77158 , 76.200775, 73.37125 , 79.70503 , 80.777115],
       [71.3531  , 72.01056 , 69.19281 , 74.09346 , 72.343155],
       [74.50927 , 75.758766, 71.63187 , 79.23577 , 74.93776 ],
       [73.298744, 74.82704 , 70.9089  , 73.97748 , 73.13696 ],
       [74.98425 , 78.72725 , 74.830414, 81.01732 , 79.28766 ]],
      dtype=float32)>

In [105]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor_c = tf.random.uniform(shape = (224,224,3),dtype= tf.float32)
tensor_c

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.43555546, 0.52486527, 0.49674678],
        [0.06710219, 0.35815144, 0.5931845 ],
        [0.8396933 , 0.32720697, 0.08762932],
        ...,
        [0.24612641, 0.9342215 , 0.05903411],
        [0.93307066, 0.512503  , 0.48924422],
        [0.97681785, 0.9894414 , 0.81736803]],

       [[0.9728149 , 0.7123945 , 0.24925625],
        [0.27054942, 0.65331674, 0.25431752],
        [0.29969907, 0.6473402 , 0.61158216],
        ...,
        [0.41850114, 0.9183353 , 0.08774114],
        [0.60710025, 0.92464304, 0.29132044],
        [0.14755595, 0.03294516, 0.8127129 ]],

       [[0.90104914, 0.00804007, 0.2443372 ],
        [0.71701133, 0.90716815, 0.21456563],
        [0.7990829 , 0.9918189 , 0.51183915],
        ...,
        [0.8509488 , 0.8159404 , 0.47705805],
        [0.07570207, 0.73422337, 0.3427385 ],
        [0.26765156, 0.38085854, 0.45572805]],

       ...,

       [[0.18761933, 0.00920856, 0.70124197],
        [0.08

In [108]:
# Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_min(tensor_c) ,  tf.reduce_max(tensor_c)

(<tf.Tensor: shape=(), dtype=float32, numpy=3.2186508e-06>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99999976>)

In [109]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor_d = tf.random.uniform(shape = (1,224,224,3),dtype= tf.float32)
tensor_d

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.14241445, 0.40161622, 0.33360183],
         [0.6816542 , 0.69087017, 0.22069418],
         [0.61336195, 0.9588975 , 0.3314948 ],
         ...,
         [0.21534526, 0.8758553 , 0.90849984],
         [0.913136  , 0.3300879 , 0.21957576],
         [0.294909  , 0.51060224, 0.41247094]],

        [[0.24516141, 0.0526433 , 0.8009639 ],
         [0.39559937, 0.91123044, 0.66148484],
         [0.62018025, 0.13185847, 0.2584139 ],
         ...,
         [0.69155025, 0.35061288, 0.7918345 ],
         [0.71887565, 0.13187587, 0.6776898 ],
         [0.91522217, 0.72013485, 0.5736792 ]],

        [[0.32997262, 0.01919758, 0.7673421 ],
         [0.37867343, 0.09564745, 0.07906318],
         [0.7100911 , 0.934427  , 0.5622425 ],
         ...,
         [0.8063401 , 0.53997624, 0.9590297 ],
         [0.7728716 , 0.5758432 , 0.53311133],
         [0.00398016, 0.15231979, 0.6468185 ]],

        ...,

        [[0.3400538 , 0.40921474, 

In [111]:
tesnor_d_squeeze = tf.squeeze(tensor_d)
tesnor_d_squeeze

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.14241445, 0.40161622, 0.33360183],
        [0.6816542 , 0.69087017, 0.22069418],
        [0.61336195, 0.9588975 , 0.3314948 ],
        ...,
        [0.21534526, 0.8758553 , 0.90849984],
        [0.913136  , 0.3300879 , 0.21957576],
        [0.294909  , 0.51060224, 0.41247094]],

       [[0.24516141, 0.0526433 , 0.8009639 ],
        [0.39559937, 0.91123044, 0.66148484],
        [0.62018025, 0.13185847, 0.2584139 ],
        ...,
        [0.69155025, 0.35061288, 0.7918345 ],
        [0.71887565, 0.13187587, 0.6776898 ],
        [0.91522217, 0.72013485, 0.5736792 ]],

       [[0.32997262, 0.01919758, 0.7673421 ],
        [0.37867343, 0.09564745, 0.07906318],
        [0.7100911 , 0.934427  , 0.5622425 ],
        ...,
        [0.8063401 , 0.53997624, 0.9590297 ],
        [0.7728716 , 0.5758432 , 0.53311133],
        [0.00398016, 0.15231979, 0.6468185 ]],

       ...,

       [[0.3400538 , 0.40921474, 0.04457414],
        [0.86

In [112]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor_e = tf.constant([10,100,20,34,56,46,10129,56,98,1999])
tf.argmax(tensor_e)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [114]:
# One-hot encode the tensor you created in 9.
tf.one_hot(tensor_e , depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### 📖 TensorFlow Fundamentals Extra-curriculum
* Read through the list of TensorFlow Python APIs, pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
* How would you calculate your grocery bill for the month and for the year using tensors?
* Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).
* Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
* Watch the video "What's a tensor?" - a great visual introduction to many of the concepts we've covered in this notebook.